---
- hosts: alotim_telephony
  remote_user: root
  become: yes
  become_user: root
  
  tasks:
      
  - name: Download and extract Asterisk sounds {{iasterisk_url_sounds}} to /tmp/
    unarchive: "src={{iasterisk_url_sounds}} dest=/tmp/sounds/ remote_src=yes"       
    
  - name: copy /tmp/sounds /var/lib/asterisk/sounds/fr
    command: 'cp -r /tmp/sounds/. /var/lib/asterisk/sounds/fr/'
    
  - name: restart asterisk
    service:
      name: asterisk
      state: restarted
      
  - meta: end_play
  ##############################################################################################################"
  
